<?php

require_once('includes/civicrm.inc');
require_once('includes/utils.inc');

function spkaderfunctiesafdeling_views_api() {
  return array('api' => 3.0);
}

function spkaderfunctiesafdeling_views_default_views() {
  civicrm_initialize();
  $files = file_scan_directory(drupal_get_path('module', 'spkaderfunctiesafdeling'). '/views', '/.inc/');
  $views = array();
  foreach ($files as $filepath => $file) {
    $view = false;
    require $filepath;
    if (!empty($view)) {
      $views[$view->name] = $view;
    }
  }
  return $views;
}

/**
 * Place a link to the view on the contact summary
 *
 * Implementation of hook_civicrm_summary
 *
 * @link http://wiki.civicrm.org/confluence/display/CRMDOC/hook_civicrm_summary
 */
function spkaderfunctiesafdeling_civicrm_pageRun(&$page) {
  if ($page instanceof CRM_Contact_Page_View_Summary) {
    $config = SpKaderfunctiesAfdelingConfigCiviCRM::getInstance();

    $afdelings_contacten = spkaderfunctiesafdeling_get_afdelingscontacten();
    $contact_id = $page->getVar('_contactId');
    if (!isset($afdelings_contacten[$contact_id])) {
      return;
    }
    $contact = civicrm_api3('Contact', 'getsingle', array('id' => $contact_id));
    if ($contact['contact_type'] != 'Organization') {
      return;
    }
    $valid_sub_types = $config->getContactSubTypesForButton();
    $valid = false;
    foreach($valid_sub_types as $sub_type) {
      if (in_array($sub_type, $contact['contact_sub_type'])) {
        $valid = true;
        break;
      }
    }

    if ($valid) {
      CRM_Core_Region::instance('page-body')->add(array(
        'markup' => '<script type="text/javascript">
            cj(function() {
              cj(\'li.crm-summary-block\').after(\'<li class="crm-view-kaderfuncties-afdeling-action crm-contact-view-kaderfuncties-afdeling"><a href="'.url('kaderfuncties-afdeling/'.$contact_id).'" class="kaderfuncties-afdeling button" title="Bekijk/Wijzig afdelingsrelaties"><span>Bekijk/Wijzig afdelingsrelaties</span></a></li>\');
            });
          </script>
        '));
    }
  }
}

/**
 * Implements hook_menu().
 */
function spkaderfunctiesafdeling_menu() {
  $items = array();
  $items['admin/config/sp/kaderfuncties-afdelingen'] = array(
    'title'            => 'Kaderfuncties afdelingen',
    'description'      => 'Instellingen voor de view Kaderfuncties afdelingen',
    'type'             => MENU_NORMAL_ITEM,
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('spkaderfunctiesafdeling_admin_settings_form'),
    'access arguments' => array('access administration pages'),
  );
  $items['kaderfuncties-afdeling/%/beeindig'] = array(
    'title'            => 'Kaderfunctie beëindigen',
    'description'      => 'Beëindig een kaderfunctie',
    'type'             => MENU_NORMAL_ITEM,
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('spkaderfunctiesafdeling_beeindig', 1),
    'access callback'  => 'spkaderfunctiesafdeling_check_relationship',
    'access arguments' => array(1),
    'weight'           => -100
  );
  $items['kaderfuncties-afdeling/nieuw'] = array(
    'title'            => 'Kaderfunctie toevoegen',
    'description'      => 'Voeg een kaderfunctie toe',
    'type'             => MENU_NORMAL_ITEM,
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('spkaderfunctiesafdeling_new'),
    'access callback'  => 'spkaderfunctiesafdeling_check_new',
    'access arguments' => array(),
    'weight'           => -100
  );
  $items['kaderfuncties-afdeling/autocomplete'] = array(
    'title' => 'Autocomplete',
    'page callback' => 'spkaderfunctiesafdeling_autocomplete',
    'access callback' => 'spkaderfunctiesafdeling_check_new',
    'access arguments' => array(),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function spkaderfunctiesafdeling_autocomplete($string="") {
  civicrm_initialize();
  $session = CRM_Core_Session::singleton();
  list($aclFrom, $aclWhere) = CRM_Contact_BAO_Contact_Permission::cacheClause('contact_a');
  $params = array();
  $sql = "SELECT contact_a.id, contact_a.display_name
          FROM civicrm_contact contact_a
          {$aclFrom}
          WHERE contact_a.contact_type = 'Individual' AND contact_a.is_deleted = 0 AND contact_a.is_deceased = 0 AND {$aclWhere}
          ";
  if (!empty($string)) {
    $sql .= " AND (contact_a.display_name LIKE %1 OR contact_a.sort_name LIKE %1 OR CONVERT(contact_a.id, CHAR) LIKE %1)";
    $params[1] = array('%'.$string.'%', 'String');
  }
  $sql .= " ORDER BY contact_a.sort_name LIMIT 0,10";
  $return = array();
  $dao = CRM_Core_DAO::executeQuery($sql, $params);
  while($dao->fetch()) {
    if ($session->getLoggedInContactID() != $dao->id) {
      $name = $dao->display_name . " (Lidnr: " . $dao->id . ")";
      $return[$name] = $name;
    }
  }
  drupal_json_output($return);
}

function spkaderfunctiesafdeling_admin_settings_form() {
  $form = array();

  $form['spkaderfunctiesafdeling_description'] = array(
    '#markup' => '<h3>Instellingen</h3><p>Geef hieronder de relaties op die via de view kaderfuncties van afdelingen mogen worden toegevoegd</p>',
  );

  $form['spkaderfunctiesafdeling_end_relationship_types'] = array(
    '#type'          => 'checkboxes',
    '#title'         => 'Relatietypes die beëindig mogen worden',
    '#default_value' => variable_get('spkaderfunctiesafdeling_end_relationship_types', array()),
    '#description'   => 'Voor deze relatietypes komt er knopje beëindig vanuit de view.',
    '#required'      => true,
    '#options'       => spkaderfunctiesafdeling_get_civicrm_relationship_types(),
  );

  $form['spkaderfunctiesafdeling_new_relationship_types'] = array(
    '#type'          => 'checkboxes',
    '#title'         => 'Relatietypes die aangemaakt mogen worden door afdelingsgebruikers',
    '#default_value' => variable_get('spkaderfunctiesafdeling_new_relationship_types', array()),
    '#description'   => 'Een afdelingsgebruiker mag voor deze relatietypes nieuwe relaties aanmaken ',
    '#required'      => true,
    '#options'       => spkaderfunctiesafdeling_get_civicrm_relationship_types(),
  );

  return system_settings_form($form);
}

function spkaderfunctiesafdeling_new($form, &$form_state) {
  civicrm_initialize();
  $relationship_types = array();
  $relationships = variable_get('spkaderfunctiesafdeling_new_relationship_types', array());
  foreach($relationships as $rel_type_id => $check) {
    if ($check) {
      $relationship_types[$rel_type_id] = civicrm_api3('RelationshipType', 'getvalue', array(
        'id' => $rel_type_id,
        'return' => 'label_a_b'
      ));
    }
  }

  $form['spkaderfunctiesafdeling_description'] = array(
    '#markup' => '<h3>Voeg een nieuwe kaderfunctie toe</h3><p>Hieronder kunt een nieuwe kaderfunctie toevoegen</p>',
  );

  $form['spkaderfunctiesafdeling_relationship_type'] = array(
    '#type'          => 'select',
    '#title'         => 'Relatietype',
    '#options'       => $relationship_types,
    '#description'   => 'Selecteer een relatietype',
    '#required'      => true,
  );

  $form['spkaderfunctiesafdeling_contact_id_b'] = array(
    '#type'          => 'select',
    '#title'         => 'Afdeling/Regio/Provincie',
    '#options'       => spkaderfunctiesafdeling_get_afdelingscontacten(),
    '#description'   => 'Selecteer afdeling/regio/provincie',
    '#required'      => true,
  );

  $form['spkaderfunctiesafdeling_contact_id_a'] = array(
    '#type' => 'textfield',
    '#title' => t('Persoon'),
    '#required'      => true,
    '#description'   => 'Selecteer een persoon',
    // The autocomplete path is provided in hook_menu in ajax_example.module.
    '#autocomplete_path' => 'kaderfuncties-afdeling/autocomplete',
  );

  $form['spkaderfunctiesafdeling_submit'] = array(
    '#type' => 'submit',
    '#value' => t('Aanmaken'),
  );

  $form['cancel']['#type'] = 'submit';
  $form['cancel']['#value'] = t('Cancel');
  $form['cancel']['#submit_type'] = 'button';
  $form['cancel']['#submit'] = array('spkaderfunctiesafdeling_cancel');
  $form['cancel']['#limit_validation_errors'] = array();
  $form['cancel']['#validate'] = array();

  return $form;
}

function spkaderfunctiesafdeling_new_validate($form, &$form_state) {
  $contact_a = $form_state['values']['spkaderfunctiesafdeling_contact_id_a'];
  $matches = array();
  preg_match("/\w+\s+\(Lidnr: (\d+)\)/i", $contact_a, $matches);
  $contact_a_id = (int) $matches[1];

  civicrm_initialize();
  $relationship_type_id = $form_state['values']['spkaderfunctiesafdeling_relationship_type'];
  try {
    $contact_a = civicrm_api3('Contact', 'getsingle', array('id' => $contact_a_id));
  } catch (Exception $e) {
    form_set_error('spkaderfunctiesafdeling_contact_id_a', t('Persoon is een verplicht veld'));
  }
  try {
    $contact_b = civicrm_api3('Contact', 'getsingle', array('id' => $form_state['values']['spkaderfunctiesafdeling_contact_id_b']));
  } catch (Exception $e) {
    form_set_error('spkaderfunctiesafdeling_contact_id_b', t('Afdeling/Regio/Provincie is verplicht'));
  }
  try {
    $relationship_type = civicrm_api3('RelationshipType', 'getsingle', array('id' => $relationship_type_id));
  } catch (Exception $e) {
    form_set_error('spkaderfunctiesafdeling_relationship_type', 'Ongeldige invoer');
  }
  if ($contact_a['contact_type'] != $relationship_type['contact_type_a'] || ($relationship_type['contact_sub_type_a'] && !in_array($relationship_type['contact_sub_type_a'], $contact_a['contact_sub_type']))) {
    form_set_error('spkaderfunctiesafdeling_contact_id_a', t('Ongeldig contact type'));
  }
  if ($contact_b['contact_type'] != $relationship_type['contact_type_b'] || ($relationship_type['contact_sub_type_b'] && !in_array($relationship_type['contact_sub_type_b'], $contact_b['contact_sub_type']))) {
    form_set_error('spkaderfunctiesafdeling_contact_id_b', t('Ongeldig contact type'));
  }

  //check if relationship al bestaat
  $relatioship = civicrm_api3('Relationship', 'get', array(
    'status_id' => CRM_Contact_BAO_Relationship::CURRENT,
    'relationship_type_id' => $relationship_type_id,
    'contact_id' => $contact_a_id
  ));
  foreach($relatioship['values'] as $rel) {
    if ($rel['contact_id_b'] == $contact_b['id'] && $rel['contact_id_a'] == $contact_a['id']) {
      form_set_error('spkaderfunctiesafdeling_relationship_type', t('Er bestaat al een actieve relatie'));
      break;
    }
  }

}

function spkaderfunctiesafdeling_new_submit($form, &$form_state) {
  $contact_a = $form_state['values']['spkaderfunctiesafdeling_contact_id_a'];
  $matches = array();
  preg_match("/\w+\s+\(Lidnr: (\d+)\)/i", $contact_a, $matches);
  $contact_a_id = (int) $matches[1];

  civicrm_initialize();
  $now = new DateTime();
  $params['relationship_type_id'] = $form_state['values']['spkaderfunctiesafdeling_relationship_type'];
  $params['contact_id_a'] = $contact_a_id;
  $params['contact_id_b'] = $form_state['values']['spkaderfunctiesafdeling_contact_id_b'];
  $params['is_active'] = 1;
  $params['start_date'] = $now->format('Ymd');

  civicrm_api3('Relationship', 'create', $params);
  spkaderfunctiesafdeling_log_activity_new_relationship($params);

  $form_state['redirect'] = 'kaderfuncties-afdeling';
}

function spkaderfunctiesafdeling_beeindig($form, &$form_state, $relationship_id) {
  $form_state['relationship_id'] = $relationship_id;

  civicrm_initialize();
  $relationship = civicrm_api3('Relationship', 'getsingle', array('id' => $relationship_id));
  $relationship_type = civicrm_api3('RelationshipType', 'getsingle', array('id' => $relationship['relationship_type_id']));
  $contact_a = civicrm_api3('Contact', 'getsingle', array('id' => $relationship['contact_id_a']));
  $contact_b = civicrm_api3('Contact', 'getsingle', array('id' => $relationship['contact_id_b']));

  $form['spkaderfunctiesafdeling_description'] = array(
    '#markup' => '<h3>Beëindig een relatie</h3><p>Weet u zeker dat u dat u deze relatie wilt beëindigen?</p>',
  );

  $form['spkaderfunctiesafdeling_relatie'] = array(
    '#markup' => '<p><strong>Contact A: </strong>'.$contact_a['display_name'].'<br><strong>Contact B: </strong> '.$contact_b['display_name'].'<br><strong>Relatietype</strong>'.$relationship_type['label_a_b'].'</p>',
  );

  $form['spkaderfunctiesafdeling_submit'] = array(
    '#type' => 'submit',
    '#value' => t('Beëindig'),
  );

  $form['cancel']['#type'] = 'submit';
  $form['cancel']['#value'] = t('Cancel');
  $form['cancel']['#submit_type'] = 'button';
  $form['cancel']['#submit'] = array('spkaderfunctiesafdeling_cancel');
  $form['cancel']['#limit_validation_errors'] = array();
  $form['cancel']['#validate'] = array();

  return $form;
}

function spkaderfunctiesafdeling_cancel($form, &$form_state) {
  $form_state['redirect'] = 'kaderfuncties-afdeling';
}

function spkaderfunctiesafdeling_beeindig_submit($form, &$form_state) {
  $now = new DateTime();
  $relationship_id = $form_state['relationship_id'];
  $params['id'] = $relationship_id;
  $params['end_date'] = $now->format('Ymd');
  civicrm_initialize();
  $relationship = civicrm_api3('Relationship', 'getsingle', array('id' => $relationship_id));
  civicrm_api3('Relationship', 'create', $params);
  spkaderfunctiesafdeling_log_activity_end_relationship($relationship);
  $form_state['redirect'] = 'kaderfuncties-afdeling';
}